name: test2
on: 
  push:
  workflow_dispatch:
jobs:
  build_first:
    runs-on: ubuntu-latest
    steps:
      - name: the first command
        run: ls -l && echo "hello there" && cat /etc/os* && uname -a && whoami
      - name: checking out repos
        uses: actions/checkout@v4
      - name: run python script
        run: python example.py
  run_terraform:
    runs-on: ubuntu-latest
    steps:
        - name: checking out repos
          uses: actions/checkout@v4
        - name: Setup terraform
          uses: hashicorp/setup-terraform@v3
        - name: Terraform init
          run: terraform init
        - name: Terraform plan
          run: terraform plan
        - name: terraform apply
          run: terraform apply -auto-approve
        - name: Listing file and contents
          run: ls -l && cat my_first_file
