name: test1
on: 
  push:
  workflow_dispatch:
jobs:
  build_first:
    runs-on: ubuntu-latest
    steps:
      - name: the first command
        run: ls -l && echo "hello there" && cat /etc/os* && uname -a && whoami
     
